### ISSUE TITLE
Fix glitch when changing dark/light theme

### ISSUE THREAD

**Issue by kutyel** [kutyel/kutyel-hakyll#18]
@rpearce did you finally blog about this? 😄

**Comment by rpearce** [comment]
@kutyel No 😞. I haven't written or done much open source since having our second daughter.

Would you find it very valuable?

**Comment by kutyel** [comment]
Congrats on the parenthood! I'd would be helpful as I could not fix it myself (not enough Hakyll knowledge, as with #5), but do not worry take your time! 😘

**Comment by rpearce** [comment]
@kutyel It is less hakyll and more CSS and JS, but I'll do it just for you.

**Comment by rpearce** [comment]
@kutyel This is a weird question, but would you be willing to [GitHub Sponsor me USD$1](https://github.com/sponsors/rpearce/), just one time, to write this article? I have not made $1 online from something I've made this year, but this could be it, and I could include at the top of the article that _you_ sponsored it.

<img width="500" alt="imagen" src="https://github.com/kutyel/kutyel-hakyll/assets/592876/a4c30e54-dfd6-4f06-b1bc-468d907e2188">

If not, then no problem, and I will write the article, anyway :)

**Comment by kutyel** [comment]
That's a great idea, I will do that, thanks again! ❤️

**Comment by kutyel** [comment]
Done! Thanks for your hakyll template and for all your OSS Haskell work! 💯

**Comment by rpearce** [comment]
I am working on it! I have a lot of work to do, but it will happen :)

<img width="1512" alt="imagen" src="https://github.com/kutyel/kutyel-hakyll/assets/592876/2c4cffe0-afd2-4647-a69c-a1bd9310e139">

**Comment by kutyel** [comment]
Awesome, looking forward to reading it! ❤️

**Comment by rpearce** [comment]
@kutyel Here is the article! https://robertwpearce.com/theming-static-sites.html

You can use the ideas from the article to alter https://github.com/kutyel/kutyel-hakyll/blob/c36b0a87daba3fe42b6364e5af461c652d6dbe96/src/templates/default.html#L42-L48 (and your CSS) to match what it is you are trying to do.

In your case, instead of listening for a change to a dropdown, you could listen to a change to the switch I think you have from my old design, and then do the same technique mentioned in this blog post. If you're only doing dark/light themes, then you could even reduce the code further, since it's a boolean (light or dark).

Please let me know if you have questions.

**Comment by kutyel** [comment]
Awesome, thanks very much! 🙌🏻

**Comment by rpearce** [comment]
I'll clone your repo tonight or tomorrow night and fix this for you

**Comment by rpearce** [comment]
@kutyel Can you describe the "glitch"? Is it a flash when changing pages?

**Comment by rpearce** [comment]
Ok, thanks! I am spending some time with family and will help fix this as soon as I can.

**Comment by rpearce** [comment]
Starting on this tonight... it might take me a little while, but we'll see.
